# Generated by Django 5.2.2 on 2025-07-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gc_messages',
            name='body',
            field=models.CharField(default='Hey!', max_length=300),
        ),
    ]
