# Generated by Django 5.2.2 on 2025-07-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SIGNUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone_number', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Education', models.CharField(max_length=50)),
            ],
        ),
    ]
